---

- include_vars: "{{ansible_distribution}}.yml"

- name: Add APT key
  apt_key: keyserver=keyserver.ubuntu.net id=EA312927
  when: '"mongodb-org" in mongodb_package'

#- name: Add APT repository
#  apt_repository: repo="{{mongodb_repository}}" update_cache=yes
#  when: '"mongodb-org" in mongodb_package'

- pause: minutes=1

- name: Add APT repository in sources list
  template: src=mongodb-org-3.2.list.j2 dest=/etc/apt/sources.list.d/mongodb-org-3.2.list mode=0666
#  when: '"mongodb-org" in mongodb_package'

- name: Install MongoDB package
  sudo: yes
  apt: force=yes pkg={{mongodb_package}} state=present

- name: Install additional packages
  apt: pkg={{item}}
  with_items: mongodb_additional_packages
