---
  tasks:
  -
  name: Add Mongo repository key.
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  -
  name: Add repository Debian
  lineinfile: "dest=/etc/apt/sources.list.d/mongodb-org.list create=yes line='deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen'"
  when: ansible_distribution == 'Debian'
  - 
  name: Add repository Ubuntu
  lineinfile: "dest=/etc/apt/sources.list.d/mongodb-org.list create=yes line='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'"
  when: ansible_distribution == 'Ubuntu'
  - 
  name: Update
  command: apt-get update
  - 
  name: Install MongoDB
  command: apt-get install -y mongodb-org
  -
  name: Start MongoDB
  command: service mongod start
  -
  name: Create collection widgets
  shell: mongo GalaxiaDB --eval "db.createCollection('widgets')"
  -
  name: Create collection selectwidgets
  shell: mongo GalaxiaDB --eval "db.createCollection('selectwidgets')"
  